name: unsloth-studio

services:
  unsloth:
    build:
      context: .
      dockerfile: Dockerfile.unsloth
    image: unsloth-core
    container_name: unsloth
    environment:
      JUPYTER_PORT: ${JUPYTER_PORT:-8888}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-unsloth}
      NOTEBOOK_DIR: ${PWD}
    network_mode: host
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ${PWD}:${PWD}
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    working_dir: ${PWD}
    gpus: all
    restart: unless-stopped

  unsloth-studio:
    build:
      context: .
      dockerfile: Dockerfile.unsloth-studio
    image: unsloth-studio
    container_name: unsloth-studio
    environment:
      SERVER_PORT: ${SERVER_PORT:-8889}
    gpus: all
    restart: unless-stopped
